import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "CalcNow terms of service. Calculator results are estimates and should not replace professional advice.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8 py-4">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        <p className="text-muted-foreground mt-2">
          Last updated: March 2026
        </p>
      </div>

      <section className="space-y-6 text-sm leading-relaxed text-muted-foreground">
        <div className="space-y-2">
          <h2 className="text-lg font-semibold text-foreground">
            Acceptance of Terms
          </h2>
          <p>
            By accessing and using CalcNow (https://www.calcnow.cc), you agree
            to be bound by these Terms of Service. If you do not agree with any
            part of these terms, please do not use our website.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-lg font-semibold text-foreground">
            Calculator Results Are Estimates
          </h2>
          <p>
            All calculator results provided on CalcNow are{" "}
            <strong className="text-foreground">estimates only</strong>. They
            are intended for informational and educational purposes and should
            not be considered professional financial, medical, legal, or any
            other type of advice.
          </p>
          <p>
            In particular, our financial calculators (including compound
            interest, loan, mortgage, salary, tip, and discount calculators)
            provide approximate figures. Actual results may vary based on
            factors such as fees, taxes, changing interest rates, and lender
            terms. Always consult a qualified financial professional before
            making financial decisions.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-lg font-semibold text-foreground">
            No Professional Advice
          </h2>
          <p>
            CalcNow does not provide professional advice of any kind. Our
            health calculators (such as the BMI calculator) are for general
            reference only and should not be used as a substitute for medical
            advice from a healthcare provider.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-lg font-semibold text-foreground">
            Limitation of Liability
          </h2>
          <p>
            CalcNow and its operators shall not be held liable for any damages,
            losses, or consequences resulting from the use of or reliance on
            any calculations, results, or information provided on this website.
            You use our calculators at your own risk.
          </p>
          <p>
            We make no warranties or representations about the accuracy,
            completeness, or reliability of the results generated by our
            calculators.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-lg font-semibold text-foreground">
            Use of the Service
          </h2>
          <p>
            CalcNow is provided free of charge for personal, non-commercial
            use. You agree not to misuse the service, attempt to disrupt its
            operation, or use it for any unlawful purpose.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-lg font-semibold text-foreground">
            Intellectual Property
          </h2>
          <p>
            All content, design, and code on CalcNow is the property of its
            operators and is protected by applicable intellectual property laws.
            You may not reproduce, distribute, or create derivative works
            without permission.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-lg font-semibold text-foreground">
            Changes to These Terms
          </h2>
          <p>
            We reserve the right to modify these terms at any time. Continued
            use of CalcNow after changes are posted constitutes acceptance of
            the updated terms.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-lg font-semibold text-foreground">Contact</h2>
          <p>
            If you have any questions about these terms, please contact us at{" "}
            <a
              href="mailto:contact@calcnow.cc"
              className="text-primary underline underline-offset-4 hover:text-primary/80"
            >
              contact@calcnow.cc
            </a>
            .
          </p>
        </div>
      </section>
    </div>
  );
}
